"""PianoCoach Generator — local web app backend (FastAPI).

Wraps generator/analyze_song.py: upload a song -> analyse -> Song Map, preview it in the
Player, then generate a standalone shareable player and export/import metadata (§18).

Run:  <venv>/Scripts/python.exe -m uvicorn webgen.server:app --port 8770
      (from the PianoCoach root)
"""
import io
import json
import os
import posixpath
import re
import shutil
import stat
import sys
import threading
import time
import uuid
import zipfile
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, Request, UploadFile
from fastapi.responses import StreamingResponse
from fastapi.staticfiles import StaticFiles

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "generator"))
import analyze_song                                    # noqa: E402

WEB = ROOT / "webgen"
UPLOADS = WEB / "uploads"; UPLOADS.mkdir(parents=True, exist_ok=True)
SAMPLES = ROOT / "samples"

app = FastAPI(title="PianoCoach Generator")
JOBS = {}                                              # job_id -> status dict


@app.middleware("http")
async def no_cache(request: Request, call_next):
    """Always revalidate (like serve_nocache.py): Save/§19 rewrites song_map.json and
    accompaniment.mp3 IN PLACE, so a heuristically-cached copy shows/plays the pre-edit song
    after the post-save reload. ETag/Last-Modified still allow cheap 304s."""
    resp = await call_next(request)
    resp.headers.setdefault("Cache-Control", "no-cache")
    return resp


def _run_analysis(job_id, audio_path, title, artist):
    j = JOBS[job_id]
    try:
        j.update(status="running", message="Analysing — stems, key, chords, melody, lyrics (a few minutes)…")
        analyze_song.analyze(str(audio_path), title, artist, use_stems=True)
        j.update(status="done", message="Done", slug=analyze_song.slugify(title))
    except Exception as e:                             # noqa: BLE001
        j.update(status="error", message=f"Failed: {e}", error=str(e))


@app.post("/api/analyze")
async def api_analyze(audio: UploadFile = File(...), title: str = Form(""), artist: str = Form("")):
    jid = uuid.uuid4().hex[:8]
    dest = UPLOADS / f"{jid}_{Path(audio.filename).name}"
    with open(dest, "wb") as f:
        shutil.copyfileobj(audio.file, f)
    ttl = (title or Path(audio.filename).stem).strip()
    JOBS[jid] = {"status": "queued", "message": "Queued", "slug": None, "title": ttl}
    threading.Thread(target=_run_analysis, args=(jid, dest, ttl, artist), daemon=True).start()
    return {"job_id": jid, "title": ttl}


@app.get("/api/job/{jid}")
async def api_job(jid: str):
    if jid not in JOBS:
        raise HTTPException(404, "no such job")
    return JOBS[jid]


@app.get("/api/catalog")
async def api_catalog():
    """List analysed songs (the catalog is the samples/ folder)."""
    out = []
    for sm in sorted(SAMPLES.glob("*/song_map.json")):
        try:
            d = json.loads(sm.read_text(encoding="utf-8"))
        except Exception:                              # noqa: BLE001
            continue
        out.append({
            "slug": sm.parent.name, "title": d.get("title"), "artist": d.get("artist"),
            "key": d.get("key"), "tempo": (d.get("tempo") or {}).get("bpm"),
            "hasLyrics": bool((d.get("lyrics") or {}).get("lines") if d.get("lyrics") else False),
            "synthetic": d.get("synthetic", False),
        })
    return out


# Player modules in dependency order (dependencies before dependents; main.js last).
_PLAYER_JS_ORDER = [
    "js/songmap.js", "js/transport.js",
    "js/renderers/keyboard.js", "js/renderers/pianoroll.js", "js/renderers/notation.js",
    "js/renderers/lyrics.js", "js/renderers/editablepianoroll.js",
    "js/main.js",
]


def _bundle_player_js():
    """Concatenate the player's ES modules into ONE classic script. The shareable zip runs
    from file://, where browsers block module scripts (CORS) and fetch — with the module
    loader gone, 'Loading…' froze forever. Each module becomes an IIFE that publishes its
    exports into a registry; import lines become destructures from it. Only the simple
    single-line named import/export forms used by the player are supported."""
    parts = ["/* PianoCoach standalone player bundle — generated by webgen (file:// safe) */",
             "var __pc_mods = {};"]
    for rel in _PLAYER_JS_ORDER:
        src = (ROOT / "player" / rel).read_text(encoding="utf-8")
        here = posixpath.dirname(rel)

        def _imp(m, _here=here):
            names, path = m.group(1).strip(), m.group(2)
            target = posixpath.normpath(posixpath.join(_here, path))
            return f'const {{ {names} }} = __pc_mods["{target}"];'

        src = re.sub(r'(?m)^import\s*\{([^}]*)\}\s*from\s*["\']([^"\']+)["\']\s*;?\s*$', _imp, src)
        if re.search(r"(?m)^import\s", src):
            raise HTTPException(500, f"player bundling: unsupported import form in {rel}")
        exports = re.findall(r"(?m)^export\s+(?:async\s+)?(?:function|class|const|let|var)\s+([$\w]+)", src)
        src = re.sub(r"(?m)^export\s+", "", src)
        parts.append(f'__pc_mods["{rel}"] = (function () {{\n"use strict";\n{src}\n'
                     f'return {{ {", ".join(exports)} }};\n}})();')
    return "\n\n".join(parts)


@app.get("/api/generate/{slug}")
async def api_generate(slug: str):
    """Package a self-contained shareable player (zip): player app + this song. Must run by
    double-clicking index.html (file://, no server), so the ES modules are bundled into a
    classic script and the Song Map is embedded inline (file:// blocks modules and fetch)."""
    song_dir = SAMPLES / slug
    sm = song_dir / "song_map.json"
    if not sm.exists():
        raise HTTPException(404, "no such song")

    # player index: swap the module loader for the embedded map + classic bundle
    idx = (ROOT / "player" / "index.html").read_text(encoding="utf-8")
    marker = '<script type="module" src="js/main.js"></script>'
    if marker not in idx:
        raise HTTPException(500, "player bundling: module script tag not found in player/index.html")
    song_json = sm.read_text(encoding="utf-8").replace("</", "<\\/")   # keep </script> inert
    idx = idx.replace(marker, f"<script>window.PC_EMBED_SONG = {song_json}; "
                              'window.PC_EMBED_BASE = "../song/";</script>\n'
                              '  <script src="js/bundle.js"></script>')

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for p in (ROOT / "player").rglob("*"):
            rel = p.relative_to(ROOT / "player").as_posix()
            if not p.is_file() or rel == "index.html" or (rel.startswith("js/") and rel.endswith(".js")):
                continue                                   # js/ is replaced by the bundle
            z.write(p, f"player/{rel}")
        z.writestr("player/index.html", idx)
        z.writestr("player/js/bundle.js", _bundle_player_js())
        for p in song_dir.rglob("*"):
            if p.is_file():
                z.write(p, f"song/{p.relative_to(song_dir)}")
        # a root index that opens the player pointed at the bundled song
        z.writestr("index.html",
                   '<!doctype html><meta charset="utf-8">'
                   '<meta http-equiv="refresh" content="0; url=player/index.html?song=../song/song_map.json">'
                   '<script>location.replace("player/index.html?song=../song/song_map.json")</script>'
                   '<p>Opening PianoCoach…</p>')
    buf.seek(0)
    return StreamingResponse(buf, media_type="application/zip",
                             headers={"Content-Disposition": f'attachment; filename="pianocoach_{slug}.zip"'})


@app.post("/api/edit/{slug}")
async def api_edit(slug: str, request: Request):
    """Apply an edited melody (§19): rewrite the Song Map + re-synthesize the accompaniment.
    Chords are left untouched. Body: {"melody": [{"t0","t1","midi"}, ...]}."""
    song_dir = SAMPLES / slug
    sm = song_dir / "song_map.json"
    if not sm.exists():
        raise HTTPException(404, "no such song")
    body = await request.json()
    edited = body.get("melody")
    if edited is None:
        raise HTTPException(400, "no melody in body")

    try:
        clean = []
        for n in edited:
            t0, t1, m = float(n["t0"]), float(n["t1"]), int(n["midi"])
            if t1 <= t0:
                continue
            clean.append({"t0": round(t0, 4), "t1": round(t1, 4), "midi": m,
                          "name": analyze_song.midi_to_name(m), "hand": "R", "clef": "treble", "part": "melody"})
        clean.sort(key=lambda x: x["t0"])

        d = json.loads(sm.read_text(encoding="utf-8"))
        d["melody"] = clean
        if body.get("instrument") in analyze_song.INSTRUMENTS:
            d["instrument"] = body["instrument"]
        dur = (d.get("source") or {}).get("duration_s") or (clean[-1]["t1"] if clean else 1)
        d["audio"] = analyze_song.render_accompaniment(clean, d.get("chords", []), dur, song_dir / "audio",
                                                       instrument=d.get("instrument", "grand"))
        d["edited"] = True
        sm.write_text(json.dumps(d, indent=2), encoding="utf-8")
    except HTTPException:
        raise
    except Exception as e:                             # noqa: BLE001 — surface the real cause as JSON
        raise HTTPException(500, f"{type(e).__name__}: {e}")
    return {"ok": True, "melody_notes": len(clean)}


def _rmtree_hard(d: Path, tries: int = 4):
    """Delete a song folder properly on Windows/OneDrive.

    `rmtree(ignore_errors=True)` used to leave behind empty <slug>/ + <slug>/audio/ skeletons:
    an audio file still held by a player/preview (or a OneDrive sync lock) makes the unlink
    fail, and the error was silently swallowed. Clear read-only bits, retry a few times with a
    short backoff, and report honestly if the folder still won't go."""
    def on_error(func, path, _exc):                    # read-only -> chmod and retry once
        try:
            os.chmod(path, stat.S_IWRITE)
            func(path)
        except OSError:
            pass

    for i in range(tries):
        shutil.rmtree(d, onerror=on_error)
        if not d.exists():
            return True
        time.sleep(0.25 * (i + 1))                     # let a transient lock clear
    return not d.exists()


@app.delete("/api/song/{slug}")
async def api_delete(slug: str):
    """Remove a song/variation from the catalog (deletes its samples/<slug> folder)."""
    d = SAMPLES / slug
    if not (d / "song_map.json").exists():
        raise HTTPException(404, "no such song")
    if not _rmtree_hard(d):
        # Don't leave a phantom catalog entry: the map is gone, so the song is out of the
        # catalog either way — but say that some files are locked rather than claiming success.
        raise HTTPException(500, f"could not fully delete {slug} — files are locked "
                                 f"(close the preview/player and try again)")
    return {"deleted": slug}


@app.post("/api/catalog/sweep")
async def api_sweep():
    """Remove leftover empty song folders (skeletons from interrupted/locked deletes)."""
    removed = []
    for p in sorted(SAMPLES.glob("*/")):
        if p.is_dir() and not (p / "song_map.json").exists() and not any(p.rglob("*.*")):
            if _rmtree_hard(p):
                removed.append(p.name)
    return {"removed": removed, "count": len(removed)}


@app.get("/api/export/{slug}")
async def api_export(slug: str):
    """Back up a player's metadata: a zip of the Song Map + the embedded reference audio.
    The accompaniment is NOT stored (re-synthesised on import). Fully portable."""
    song_dir = SAMPLES / slug
    sm = song_dir / "song_map.json"
    if not sm.exists():
        raise HTTPException(404, "no such song")
    d = json.loads(sm.read_text(encoding="utf-8"))
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("song_map.json", sm.read_text(encoding="utf-8"))
        ref = (d.get("reference") or {}).get("audio")
        if ref:
            rp = song_dir / "audio" / ref.split("/")[-1]
            if rp.exists():
                z.write(rp, f"reference/{rp.name}")
    buf.seek(0)
    return StreamingResponse(buf, media_type="application/zip",
                             headers={"Content-Disposition": f'attachment; filename="PianoCoach_export_{slug}.zip"'})


def _find_song_map(z: zipfile.ZipFile) -> str:
    """Locate song_map.json in either kind of zip the Generator produces.

    /api/export puts it at the root; /api/generate (the shareable player) puts it at
    song/song_map.json. Import used to hard-code the root name, so importing a downloaded
    player -- exactly what the UI invites -- failed with "no item named 'song_map.json'".
    Take the shallowest match so a stray nested copy can't win."""
    names = [n for n in z.namelist() if not n.endswith("/")]
    cands = [n for n in names if posixpath.basename(n) == "song_map.json"]
    if not cands:
        raise HTTPException(400, "not a PianoCoach file: no song_map.json inside. Expected a "
                                 "metadata export or a downloaded player .zip.")
    return min(cands, key=lambda n: (n.count("/"), len(n)))


def _find_reference(z: zipfile.ZipFile, d: dict):
    """Find the bundled original recording. The metadata export stores it under reference/;
    the player zip keeps it beside the accompaniment in song/audio/. Match on the filename the
    Song Map already points at, then fall back to the export layout."""
    want = posixpath.basename(((d.get("reference") or {}).get("audio") or ""))
    names = [n for n in z.namelist() if not n.endswith("/")]
    if want:
        for n in names:
            if posixpath.basename(n) == want:
                return n
    refs = [n for n in names if n.startswith("reference/")]
    return refs[0] if refs else None


@app.post("/api/import")
async def api_import(metadata: UploadFile = File(...)):
    """Import a metadata backup OR a downloaded player .zip -> re-generate the song folder
    (re-synth accompaniment, restore reference). No re-analysis. Returns the slug."""
    try:
        z = zipfile.ZipFile(io.BytesIO(await metadata.read()))
    except Exception as e:                             # noqa: BLE001
        raise HTTPException(400, f"not a readable .zip file: {e}")

    entry = _find_song_map(z)
    try:
        d = json.loads(z.read(entry))
    except Exception as e:                             # noqa: BLE001
        raise HTTPException(400, f"{entry} in the archive is not valid JSON: {e}")

    slug = analyze_song.slugify(d.get("title") or "imported")
    song_dir = SAMPLES / slug
    (song_dir / "audio").mkdir(parents=True, exist_ok=True)

    dur = (d.get("source") or {}).get("duration_s") or (d["melody"][-1]["t1"] if d.get("melody") else 1)
    d["audio"] = analyze_song.render_accompaniment(d.get("melody", []), d.get("chords", []), dur, song_dir / "audio",
                                                   instrument=d.get("instrument", "grand"))

    ref_entry = _find_reference(z, d) if d.get("reference") else None
    if ref_entry:
        rn = posixpath.basename(ref_entry)
        (song_dir / "audio" / rn).write_bytes(z.read(ref_entry))
        d["reference"]["audio"] = f"audio/{rn}"
    else:
        d["reference"] = None
    (song_dir / "song_map.json").write_text(json.dumps(d, indent=2), encoding="utf-8")
    return {"slug": slug}


@app.post("/api/transpose")
async def api_transpose(slug: str = Form(...), semitones: int = Form(...)):
    """Create a transposed variant of an analysed song (fast — re-synth, no re-analysis)."""
    if not (SAMPLES / slug / "song_map.json").exists():
        raise HTTPException(404, "no such song")
    if int(semitones) == 0:
        return {"slug": slug}
    try:
        vslug = analyze_song.transpose_song(slug, int(semitones))
    except Exception as e:                             # noqa: BLE001
        raise HTTPException(500, f"transpose failed: {e}")
    return {"slug": vslug}


# --- static: the generator UI, the Player (for preview), and the samples ---
app.mount("/player", StaticFiles(directory=str(ROOT / "player")), name="player")
app.mount("/samples", StaticFiles(directory=str(SAMPLES)), name="samples")
app.mount("/", StaticFiles(directory=str(WEB / "static"), html=True), name="ui")
